**************************************************
* traduction broadcast_text pour les serveurs fr *
*     uniquement si vous avez des problémmes     *
*             de traductions                     *
**************************************************


UPDATE `broadcast_text` SET `MaleText` = 'Faites de cette auberge votre foyer', `FemaleText` = 'Faites de cette auberge votre foyer' WHERE `ID` = 2822 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je voudrais regarder vos articles.', `FemaleText` = 'Je voudrais regarder vos articles.' WHERE `ID` = 3370 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je suis prêt.', `FemaleText` = 'Je suis prête.' WHERE `ID` = 35320 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je suis prêt.', `FemaleText` = 'Je suis prête.' WHERE `ID` = 35539 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je suis prêt.', `FemaleText` = 'Je suis prête.' WHERE `ID` = 39152 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Coiffeur', `FemaleText` = 'Coiffeur' WHERE `ID` = 31340 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Coiffeur', `FemaleText` = 'Coiffeur' WHERE `ID` = 45376 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'L\'hôtel des ventes', `FemaleText` = 'L\'hôtel des ventes' WHERE `ID` = 44627 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'L\'hôtel des ventes', `FemaleText` = 'L\'hôtel des ventes' WHERE `ID` = 5316 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'L\'hôtel des ventes', `FemaleText` = 'L\'hôtel des ventes' WHERE `ID` = 5423 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'L\'hôtel des ventes', `FemaleText` = 'L\'hôtel des ventes' WHERE `ID` = 5515 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'L\'hôtel des ventes', `FemaleText` = 'L\'hôtel des ventes' WHERE `ID` = 5913 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'L\'hôtel des ventes', `FemaleText` = 'L\'hôtel des ventes' WHERE `ID` = 6369 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'L\'hôtel des ventes', `FemaleText` = 'L\'hôtel des ventes' WHERE `ID` = 15208 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'L\'hôtel des ventes', `FemaleText` = 'L\'hôtel des ventes' WHERE `ID` = 32174 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'L’auberge', `FemaleText` = 'L’auberge' WHERE `ID` = 7075 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'L’auberge', `FemaleText` = 'L’auberge' WHERE `ID` = 4893 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'L’auberge', `FemaleText` = 'L’auberge' WHERE `ID` = 5090 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'L’auberge', `FemaleText` = 'L’auberge' WHERE `ID` = 5334 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'L’auberge', `FemaleText` = 'L’auberge' WHERE `ID` = 6721 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'L’auberge', `FemaleText` = 'L’auberge' WHERE `ID` = 6791 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'L’auberge', `FemaleText` = 'L’auberge' WHERE `ID` = 6996 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Où voulez-vous aller ?', `FemaleText` = 'Où voulez-vous aller ?' WHERE `ID` = 91453 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Minage', `FemaleText` = 'Minage' WHERE `ID` = 2944 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des écuries', `FemaleText` = 'Maître des écuries' WHERE `ID` = 45383 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des écuries', `FemaleText` = 'Maître des écuries' WHERE `ID` = 8511 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des écuries', `FemaleText` = 'Maître des écuries' WHERE `ID` = 8518 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des écuries', `FemaleText` = 'Maître des écuries' WHERE `ID` = 8524 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des écuries', `FemaleText` = 'Maître des écuries' WHERE `ID` = 8525 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des écuries', `FemaleText` = 'Maître des écuries' WHERE `ID` = 8529 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des écuries', `FemaleText` = 'Maître des écuries' WHERE `ID` = 8534 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des écuries', `FemaleText` = 'Maître des écuries' WHERE `ID` = 8536 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des écuries', `FemaleText` = 'Maître des écuries' WHERE `ID` = 8539 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des écuries', `FemaleText` = 'Maître des écuries' WHERE `ID` = 8542 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des écuries', `FemaleText` = 'Maître des écuries' WHERE `ID` = 15228 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des écuries', `FemaleText` = 'Maître des écuries' WHERE `ID` = 19208 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des écuries', `FemaleText` = 'Maître des écuries' WHERE `ID` = 8508 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Banque de Forgefer', `FemaleText` = 'Banque de Forgefer' WHERE `ID` = 5078 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Port de Hurlevent', `FemaleText` = 'Port de Hurlevent' WHERE `ID` = 29416 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Le Tram des profondeurs', `FemaleText` = 'Le Tram des profondeurs' WHERE `ID` = 6328 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Le Tram des profondeurs', `FemaleText` = 'Le Tram des profondeurs' WHERE `ID` = 6351 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des griffons', `FemaleText` = 'Maître des griffons' WHERE `ID` = 6908 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des griffons', `FemaleText` = 'Maître des griffons' WHERE `ID` = 6990 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des griffons', `FemaleText` = 'Maître des griffons' WHERE `ID` = 5081 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître et marchand des guildes', `FemaleText` = 'Maître et marchand des guildes' WHERE `ID` = 45380 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître et marchand des guildes', `FemaleText` = 'Maître et marchand des guildes' WHERE `ID` = 5086 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître et marchand des guildes', `FemaleText` = 'Maître et marchand des guildes' WHERE `ID` = 5332 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître et marchand des guildes', `FemaleText` = 'Maître et marchand des guildes' WHERE `ID` = 5910 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître et marchand des guildes', `FemaleText` = 'Maître et marchand des guildes' WHERE `ID` = 6909 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître et marchand des guildes', `FemaleText` = 'Maître et marchand des guildes' WHERE `ID` = 6993 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître et marchand des guildes', `FemaleText` = 'Maître et marchand des guildes' WHERE `ID` = 15222 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître et marchand des guildes', `FemaleText` = 'Maître et marchand des guildes' WHERE `ID` = 32189 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître et marchand des guildes', `FemaleText` = 'Maître et marchand des guildes' WHERE `ID` = 2870 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Maître et marchand des guildes', `FemaleText` = 'Maître et marchand des guildes' WHERE `ID` = 3428 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître et marchand des guildes', `FemaleText` = 'Maître et marchand des guildes' WHERE `ID` = 4890 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Le maître des guildes & marchand.', `FemaleText` = 'Le maître des guildes & marchand.' WHERE `ID` = 7072 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Serrurier', `FemaleText` = 'Serrurier' WHERE `ID` = 33141 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître d\'armes', `FemaleText` = 'Maître d\'armes' WHERE `ID` = 7241 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître d\'armes', `FemaleText` = 'Maître d\'armes' WHERE `ID` = 7244 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître d\'armes', `FemaleText` = 'Maître d\'armes' WHERE `ID` = 7247 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de guerre', `FemaleText` = 'Maître de guerre' WHERE `ID` = 10359 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de guerre', `FemaleText` = 'Maître de guerre' WHERE `ID` = 10362 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de guerre', `FemaleText` = 'Maître de guerre' WHERE `ID` = 10365 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de guerre', `FemaleText` = 'Maître de guerre' WHERE `ID` = 10403 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de guerre', `FemaleText` = 'Maître de guerre' WHERE `ID` = 10411 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de guerre', `FemaleText` = 'Maître de guerre' WHERE `ID` = 10424 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de guerre', `FemaleText` = 'Maître de guerre' WHERE `ID` = 19209 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Les maîtres de guerre', `FemaleText` = 'Les maîtres de guerre' WHERE `ID` = 15232 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Les maîtres de guerre', `FemaleText` = 'Les maîtres de guerre' WHERE `ID` = 32197 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Les maîtres de guerre', `FemaleText` = 'Les maîtres de guerre' WHERE `ID` = 45377 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de métier', `FemaleText` = 'Maître de métier' WHERE `ID` = 7095 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de métier', `FemaleText` = 'Maître de métier' WHERE `ID` = 19210 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de métier', `FemaleText` = 'Maître de métier' WHERE `ID` = 45382 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de métier', `FemaleText` = 'Maître de métier' WHERE `ID` = 2869 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de métier', `FemaleText` = 'Maître de métier' WHERE `ID` = 3430 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de métier', `FemaleText` = 'Maître de métier' WHERE `ID` = 4896 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de métier', `FemaleText` = 'Maître de métier' WHERE `ID` = 5112 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de métier', `FemaleText` = 'Maître de métier' WHERE `ID` = 5352 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de métier', `FemaleText` = 'Maître de métier' WHERE `ID` = 5916 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de métier', `FemaleText` = 'Maître de métier' WHERE `ID` = 6635 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de métier', `FemaleText` = 'Maître de métier' WHERE `ID` = 6912 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de métier', `FemaleText` = 'Maître de métier' WHERE `ID` = 7022 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de métier', `FemaleText` = 'Maître de métier' WHERE `ID` = 15250 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Un maître de métier', `FemaleText` = 'Un maître de métier' WHERE `ID` = 6723 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Un maître de métier', `FemaleText` = 'Un maître de métier' WHERE `ID` = 6793 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de classe', `FemaleText` = 'Maître de classe' WHERE `ID` = 32202 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de classe', `FemaleText` = 'Maître de classe' WHERE `ID` = 2868 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de classe', `FemaleText` = 'Maître de classe' WHERE `ID` = 3429 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de classe', `FemaleText` = 'Maître de classe' WHERE `ID` = 4891 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de classe', `FemaleText` = 'Maître de classe' WHERE `ID` = 5088 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de classe', `FemaleText` = 'Maître de classe' WHERE `ID` = 5360 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de classe', `FemaleText` = 'Maître de classe' WHERE `ID` = 5915 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de classe', `FemaleText` = 'Maître de classe' WHERE `ID` = 6634 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de classe', `FemaleText` = 'Maître de classe' WHERE `ID` = 6911 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de classe', `FemaleText` = 'Maître de classe' WHERE `ID` = 6999 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de classe', `FemaleText` = 'Maître de classe' WHERE `ID` = 7078 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de classe', `FemaleText` = 'Maître de classe' WHERE `ID` = 15234 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de classe', `FemaleText` = 'Maître de classe' WHERE `ID` = 45378 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je voudrais oublier mes talents.', `FemaleText` = 'Je voudrais oublier mes talents.' WHERE `ID` = 8271 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je voudrais oublier mes talents.', `FemaleText` = 'Je voudrais oublier mes talents.' WHERE `ID` = 29630 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je voudrais oublier mes talents.', `FemaleText` = 'Je voudrais oublier mes talents.' WHERE `ID` = 62295 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des zeppelins', `FemaleText` = 'Maître des zeppelins' WHERE `ID` = 5518 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des zeppelins', `FemaleText` = 'Maître des zeppelins' WHERE `ID` = 5914 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.', `FemaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.' WHERE `ID` = 9818 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.', `FemaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.' WHERE `ID` = 12631 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.', `FemaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.' WHERE `ID` = 13966 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.', `FemaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.' WHERE `ID` = 14925 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.', `FemaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.' WHERE `ID` = 15955 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.', `FemaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.' WHERE `ID` = 16125 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.', `FemaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.' WHERE `ID` = 16127 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.', `FemaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.' WHERE `ID` = 17085 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.', `FemaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.' WHERE `ID` = 18217 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.', `FemaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.' WHERE `ID` = 19466 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.', `FemaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.' WHERE `ID` = 38807 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.', `FemaleText` = 'Je veux jeter un coup d\'œil à vos marchandises.' WHERE `ID` = 4424 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = '<S\'installer sur le plan de travail et laisser Walt vous mettre le costume de golem.>', `FemaleText` = '<S\'installer sur le plan de travail et laisser Walt vous mettre le costume de golem.>' WHERE `ID` = 23872 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'J\'aimerais suivre un entraînement.', `FemaleText` = 'J\'aimerais suivre un entraînement.' WHERE `ID` = 8221 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'J\'aimerais suivre un entraînement.', `FemaleText` = 'J\'aimerais suivre un entraînement.' WHERE `ID` = 2548 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'J\'aimerais suivre un entraînement.', `FemaleText` = 'J\'aimerais suivre un entraînement.' WHERE `ID` = 5597 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Laissez-moi jeter un coup d\'œil sur vos marchandises.', `FemaleText` = 'Laissez-moi jeter un coup d\'œil sur vos marchandises.' WHERE `ID` = 7509 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Laissez-moi jeter un coup d\'œil sur vos marchandises.', `FemaleText` = 'Laissez-moi jeter un coup d\'œil sur vos marchandises.' WHERE `ID` = 8097 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Permettez-moi de jeter un œil à vos biens.', `FemaleText` = 'Permettez-moi de jeter un œil à vos biens.' WHERE `ID` = 2823 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Un bonbon ou une blague !', `FemaleText` = 'Un bonbon ou une blague !' WHERE `ID` = 10693 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je désire créer une bannière de guilde.', `FemaleText` = 'Je désire créer une bannière de guilde.' WHERE `ID` = 3415 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je cherche une formation de druide.', `FemaleText` = 'Je cherche une formation de druide.' WHERE `ID` = 7452 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Comment puis-je former une guilde ?', `FemaleText` = 'Comment puis-je former une guilde ?' WHERE `ID` = 3413 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je dois voyager.', `FemaleText` = 'Je dois voyager.' WHERE `ID` = 3409 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Montrez-moi où je peux voler.', `FemaleText` = 'Montrez-moi où je peux voler.' WHERE `ID` = 12271 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Entraînez-moi.', `FemaleText` = 'Entraînez-moi.' WHERE `ID` = 3266 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Continuez.', `FemaleText` = 'Continuez.' WHERE `ID` = 24899 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Continuez.', `FemaleText` = 'Continuez.' WHERE `ID` = 83453 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'J’aimerais une formation.', `FemaleText` = 'J’aimerais une formation.' WHERE `ID` = 2603 AND `Language` = 1;
UPDATE `broadcast_text` SET `MaleText` = 'Parlez-moi des métiers de récolte.', `FemaleText` = 'Parlez-moi des métiers de récolte.' WHERE `ID` = 47106 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'J’aimerais me rendre sur le champ de bataille.', `FemaleText` = 'J’aimerais me rendre sur le champ de bataille.' WHERE `ID` = 10355 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je suis intéressé par une formation de mage.', `FemaleText` = 'Je suis intéressé par une formation de mage.' WHERE `ID` = 2522 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Prendre la lettre.', `FemaleText` = 'Prendre la lettre.' WHERE `ID` = 78074 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Étouffez le feu de joie de la Horde !', `FemaleText` = 'Étouffez le feu de joie de la Horde !' WHERE `ID` = 24526 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Étouffez le feu de joie de l\'Alliance !', `FemaleText` = 'Étouffez le feu de joie de l\'Alliance !' WHERE `ID` = 24530 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je suis paré au combat !', `FemaleText` = 'Je suis paré au combat !' WHERE `ID` = 33430 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Où est l\'Ancien Haute-Montagne ?', `FemaleText` = 'Où est l\'Ancien Haute-Montagne ?' WHERE `ID` = 11578 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = '<Continuer la lecture…>', `FemaleText` = '<Continuer la lecture…>' WHERE `ID` = 53903 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Couture', `FemaleText` = 'Couture' WHERE `ID` = 2951 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Couture', `FemaleText` = 'Couture' WHERE `ID` = 3469 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Couture', `FemaleText` = 'Couture' WHERE `ID` = 4871 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Couture', `FemaleText` = 'Couture' WHERE `ID` = 5144 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Couture', `FemaleText` = 'Couture' WHERE `ID` = 5380 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Couture', `FemaleText` = 'Couture' WHERE `ID` = 5900 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Couture', `FemaleText` = 'Couture' WHERE `ID` = 6629 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Couture', `FemaleText` = 'Couture' WHERE `ID` = 6717 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Couture', `FemaleText` = 'Couture' WHERE `ID` = 6787 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Couture', `FemaleText` = 'Couture' WHERE `ID` = 6956 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Couture', `FemaleText` = 'Couture' WHERE `ID` = 7035 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Couture', `FemaleText` = 'Couture' WHERE `ID` = 7121 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Couture', `FemaleText` = 'Couture' WHERE `ID` = 15275 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Couture', `FemaleText` = 'Couture' WHERE `ID` = 32148 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Couture', `FemaleText` = 'Couture' WHERE `ID` = 45760 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Couture', `FemaleText` = 'Couture' WHERE `ID` = 52077 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Parlez-moi d\'autre chose…', `FemaleText` = 'Parlez-moi d\'autre chose…' WHERE `ID` = 9293 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Parlez-moi encore des tours…', `FemaleText` = 'Parlez-moi encore des tours…' WHERE `ID` = 9290 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je cherche un entraînement pour utiliser une monture.', `FemaleText` = 'Je cherche un entraînement pour utiliser une monture.' WHERE `ID` = 7548 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je vous défie, chevalier de la mort !', `FemaleText` = 'Je vous défie, chevalier de la mort !' WHERE `ID` = 29255 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Oui, s’il vous plaît !', `FemaleText` = 'Oui, s’il vous plaît !' WHERE `ID` = 32024 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Oui, s’il vous plaît !', `FemaleText` = 'Oui, s’il vous plaît !' WHERE `ID` = 29565 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Veuillez m\'apprendre.', `FemaleText` = 'Veuillez m\'apprendre.' WHERE `ID` = 8442 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Où est l\'Ancienne Tissétoile ?', `FemaleText` = 'Où est l\'Ancienne Tissétoile ?' WHERE `ID` = 11561 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Secourisme', `FemaleText` = 'Secourisme' WHERE `ID` = 15261 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Secourisme', `FemaleText` = 'Secourisme' WHERE `ID` = 19238 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Secourisme', `FemaleText` = 'Secourisme' WHERE `ID` = 45765 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Secourisme', `FemaleText` = 'Secourisme' WHERE `ID` = 52066 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Secourisme', `FemaleText` = 'Secourisme' WHERE `ID` = 2949 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Secourisme', `FemaleText` = 'Secourisme' WHERE `ID` = 3464 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Secourisme', `FemaleText` = 'Secourisme' WHERE `ID` = 4863 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Secourisme', `FemaleText` = 'Secourisme' WHERE `ID` = 5125 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Secourisme', `FemaleText` = 'Secourisme' WHERE `ID` = 5366 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Secourisme', `FemaleText` = 'Secourisme' WHERE `ID` = 5894 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Secourisme', `FemaleText` = 'Secourisme' WHERE `ID` = 6623 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Secourisme', `FemaleText` = 'Secourisme' WHERE `ID` = 6710 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Secourisme', `FemaleText` = 'Secourisme' WHERE `ID` = 6781 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Secourisme', `FemaleText` = 'Secourisme' WHERE `ID` = 6950 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Secourisme', `FemaleText` = 'Secourisme' WHERE `ID` = 7029 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Secourisme', `FemaleText` = 'Secourisme' WHERE `ID` = 7106 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = '<Tournez la page.>', `FemaleText` = '<Tournez la page.>' WHERE `ID` = 14429 AND `Language` =35 ;
UPDATE `broadcast_text` SET `MaleText` = 'Que puis-je faire dans une auberge ?', `FemaleText` = 'Que puis-je faire dans une auberge ?' WHERE `ID` = 4308 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Montrez-moi où est le cimetière d\'Ouestincelle.', `FemaleText` = 'Montrez-moi où est le cimetière d\'Ouestincelle.' WHERE `ID` = 32434 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Montrez-moi vos marchandises.', `FemaleText` = 'Montrez-moi vos marchandises.' WHERE `ID` = 20225 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'J’aimerais vous acheter quelque chose.', `FemaleText` = 'J’aimerais vous acheter quelque chose.' WHERE `ID` = 2583 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'J’aimerais vous acheter quelque chose.', `FemaleText` = 'J’aimerais vous acheter quelque chose.' WHERE `ID` = 6399 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'J’aimerais vous acheter quelque chose.', `FemaleText` = 'J’aimerais vous acheter quelque chose.' WHERE `ID` = 7142 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'J’aimerais vous acheter quelque chose.', `FemaleText` = 'J’aimerais vous acheter quelque chose.' WHERE `ID` = 9992 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'J’aimerais vous acheter quelque chose.', `FemaleText` = 'J’aimerais vous acheter quelque chose.' WHERE `ID` = 14967 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Où est l\'Ancien Barbe-de-Bronze ?', `FemaleText` = 'Où est l\'Ancien Barbe-de-Bronze ?' WHERE `ID` = 11512 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Où est l\'ancien Arp ?', `FemaleText` = 'Où est l\'ancien Arp ?' WHERE `ID` = 31252 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Où est l\'ancien Lunaro ?', `FemaleText` = 'Où est l\'ancien Lunaro ?' WHERE `ID` = 31290 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Où est l\'ancien Pamuya ?', `FemaleText` = 'Où est l\'ancien Pamuya ?' WHERE `ID` = 31255 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Où est l\'Ancien Cri-du-Marteau ?', `FemaleText` = 'Où est l\'Ancien Cri-du-Marteau ?' WHERE `ID` = 11550 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Boîte aux lettres', `FemaleText` = 'Boîte aux lettres' WHERE `ID` = 4895 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Boîte aux lettres', `FemaleText` = 'Boîte aux lettres' WHERE `ID` = 5093 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Boîte aux lettres', `FemaleText` = 'Boîte aux lettres' WHERE `ID` = 5336 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Boîte aux lettres', `FemaleText` = 'Boîte aux lettres' WHERE `ID` = 5514 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Boîte aux lettres', `FemaleText` = 'Boîte aux lettres' WHERE `ID` = 5912 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Apprenez-moi l\'herboristerie.', `FemaleText` = 'Apprenez-moi l\'herboristerie.' WHERE `ID` = 47112 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'J\'ai besoin d\'un cheval.', `FemaleText` = 'J\'ai besoin d\'un cheval.' WHERE `ID` = 38635 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'J’ai compris.', `FemaleText` = 'J’ai compris.' WHERE `ID` = 53318 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'J’ai compris.', `FemaleText` = 'J’ai compris.' WHERE `ID` = 60548 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Apprenez-moi l\'ingénierie.', `FemaleText` = 'Apprenez-moi l\'ingénierie.' WHERE `ID` = 47119 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Ingrédients et fournitures magiques', `FemaleText` = 'Ingrédients et fournitures magiques' WHERE `ID` = 32717 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je suis ici pour récupérer votre rapport.', `FemaleText` = 'Je suis ici pour récupérer votre rapport.' WHERE `ID` = 11325 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = '<Prenez ce livre pour le bien d’Azeroth !>', `FemaleText` = '<Prenez ce livre pour le bien d’Azeroth !>' WHERE `ID` = 11114 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je voudrais jeter un œil à vos marchandises, intendant.', `FemaleText` = 'Je voudrais jeter un œil à vos marchandises, intendant.' WHERE `ID` = 47622 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Auberge du quartier des Nains', `FemaleText` = 'Auberge du quartier des Nains' WHERE `ID` = 44604 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Banque', `FemaleText` = 'Banque' WHERE `ID` = 3426 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Banque', `FemaleText` = 'Banque' WHERE `ID` = 5908 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Banque', `FemaleText` = 'Banque' WHERE `ID` = 6631 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Banque', `FemaleText` = 'Banque' WHERE `ID` = 6907 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Banque', `FemaleText` = 'Banque' WHERE `ID` = 6987 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Banque', `FemaleText` = 'Banque' WHERE `ID` = 15214 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Banque', `FemaleText` = 'Banque' WHERE `ID` = 19201 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Banque', `FemaleText` = 'Banque' WHERE `ID` = 32167 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Banque', `FemaleText` = 'Banque' WHERE `ID` = 44628 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Banque', `FemaleText` = 'Banque' WHERE `ID` = 78584 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Auberge', `FemaleText` = 'Auberge' WHERE `ID` = 6910 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Calligraphie', `FemaleText` = 'Calligraphie' WHERE `ID` = 45757 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Calligraphie', `FemaleText` = 'Calligraphie' WHERE `ID` = 48811 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Calligraphie', `FemaleText` = 'Calligraphie' WHERE `ID` = 31542 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Calligraphie', `FemaleText` = 'Calligraphie' WHERE `ID` = 32146 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Salut à vous, $gchampion:championne;. Les récits de vos exploits seront contés à travers les âges. Un jour, votre statue prendra peut-être place parmi celles des héros de Hurlevent.' WHERE `ID` = 14390 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Pourquoi ne vous échappez-vous pas ?', `FemaleText` = 'Pourquoi ne vous échappez-vous pas ?' WHERE `ID` = 16485 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Circulez, $gcitoyen:citoyenne;. Il n\'y a rien à voir.' WHERE `ID` = 9875 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Welcome to the Stormwind Guild Registry offices. What can I help you with today?', 'Welcome to the Stormwind Guild Registry offices. What can I help you with today?' WHERE `ID` = 3412 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Je souhaite apprendre la double spécialisation.', `FemaleText` = 'Je souhaite apprendre la double spécialisation.' WHERE `ID` = 33765 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je suis intéressé par une formation de démoniste.', `FemaleText` = 'Je suis intéressé par une formation de démoniste.' WHERE `ID` = 2544 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Ingénierie', `FemaleText` = 'Ingénierie' WHERE `ID` = 2943 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Ingénierie', `FemaleText` = 'Ingénierie' WHERE `ID` = 4976 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Ingénierie', `FemaleText` = 'Ingénierie' WHERE `ID` = 5123 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Ingénierie', `FemaleText` = 'Ingénierie' WHERE `ID` = 5893 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Ingénierie', `FemaleText` = 'Ingénierie' WHERE `ID` = 6622 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Ingénierie', `FemaleText` = 'Ingénierie' WHERE `ID` = 6780 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Ingénierie', `FemaleText` = 'Ingénierie' WHERE `ID` = 6949 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Ingénierie', `FemaleText` = 'Ingénierie' WHERE `ID` = 7028 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Ingénierie', `FemaleText` = 'Ingénierie' WHERE `ID` = 15259 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Ingénierie', `FemaleText` = 'Ingénierie' WHERE `ID` = 32143 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Ingénierie', `FemaleText` = 'Ingénierie' WHERE `ID` = 45756 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Ingénierie', `FemaleText` = 'Ingénierie' WHERE `ID` = 51347 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Enchantement', `FemaleText` = 'Enchantement' WHERE `ID` = 52063 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Enchantement', `FemaleText` = 'Enchantement' WHERE `ID` = 3006 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Enchantement', `FemaleText` = 'Enchantement' WHERE `ID` = 3463 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Enchantement', `FemaleText` = 'Enchantement' WHERE `ID` = 4862 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Enchantement', `FemaleText` = 'Enchantement' WHERE `ID` = 5121 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Enchantement', `FemaleText` = 'Enchantement' WHERE `ID` = 5363 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Enchantement', `FemaleText` = 'Enchantement' WHERE `ID` = 5892 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Enchantement', `FemaleText` = 'Enchantement' WHERE `ID` = 6621 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Enchantement', `FemaleText` = 'Enchantement' WHERE `ID` = 6709 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Enchantement', `FemaleText` = 'Enchantement' WHERE `ID` = 6779 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Enchantement', `FemaleText` = 'Enchantement' WHERE `ID` = 6948 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Enchantement', `FemaleText` = 'Enchantement' WHERE `ID` = 7027 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Enchantement', `FemaleText` = 'Enchantement' WHERE `ID` = 7103 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Enchantement', `FemaleText` = 'Enchantement' WHERE `ID` = 15257 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Enchantement', `FemaleText` = 'Enchantement' WHERE `ID` = 19234 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Enchantement', `FemaleText` = 'Enchantement' WHERE `ID` = 45755 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Guerrier', `FemaleText` = 'Guerrier' WHERE `ID` = 45408 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Guerrier', `FemaleText` = 'Guerrier' WHERE `ID` = 2910 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Guerrier', `FemaleText` = 'Guerrier' WHERE `ID` = 3451 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Guerrier', `FemaleText` = 'Guerrier' WHERE `ID` = 4887 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Guerrier', `FemaleText` = 'Guerrier' WHERE `ID` = 5110 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Guerrier', `FemaleText` = 'Guerrier' WHERE `ID` = 5350 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Guerrier', `FemaleText` = 'Guerrier' WHERE `ID` = 5906 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Guerrier', `FemaleText` = 'Guerrier' WHERE `ID` = 6616 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Guerrier', `FemaleText` = 'Guerrier' WHERE `ID` = 6704 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Guerrier', `FemaleText` = 'Guerrier' WHERE `ID` = 6774 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Guerrier', `FemaleText` = 'Guerrier' WHERE `ID` = 6938 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Guerrier', `FemaleText` = 'Guerrier' WHERE `ID` = 7019 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Guerrier', `FemaleText` = 'Guerrier' WHERE `ID` = 7092 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je voudrais parfaire mon apprentissage.', `FemaleText` = 'Je voudrais parfaire mon apprentissage.' WHERE `ID` = 7149 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je voudrais parfaire mon apprentissage.', `FemaleText` = 'Je voudrais parfaire mon apprentissage.' WHERE `ID` = 7514 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je voudrais parfaire mon apprentissage.', `FemaleText` = 'Je voudrais parfaire mon apprentissage.' WHERE `ID` = 7528 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Comment apprendre la double spécialisation ?', `FemaleText` = 'Comment apprendre la double spécialisation ?' WHERE `ID` = 33762 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je souhaiterais recevoir un entraînement de guerrier.', `FemaleText` = 'Je souhaiterais recevoir un entraînement de guerrier.' WHERE `ID` = 3147 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je voudrais maîtriser de nouvelles armes.', `FemaleText` = 'Je voudrais maîtriser de nouvelles armes.' WHERE `ID` = 8811 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Continuez, je vous prie.', `FemaleText` = 'Continuez, je vous prie.' WHERE `ID` = 12031 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Continuez, je vous prie.', `FemaleText` = 'Continuez, je vous prie.' WHERE `ID` = 4247 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Continuez, je vous prie.', `FemaleText` = 'Continuez, je vous prie.' WHERE `ID` = 12025 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Continuez, je vous prie.', `FemaleText` = 'Continuez, je vous prie.' WHERE `ID` = 12029 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Enseignez-moi la voie des Esprits.', `FemaleText` = 'Enseignez-moi la voie des Esprits.' WHERE `ID` = 7658 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Puis-je avoir un autre bélier de course ?', `FemaleText` = 'Puis-je avoir un autre bélier de course ?' WHERE `ID` = 74294 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'J\'aimerais mettre mon familier à l\'écurie.', `FemaleText` = 'J\'aimerais mettre mon familier à l\'écurie.' WHERE `ID` = 30181 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Vous avez du ravitaillement ?', `FemaleText` = 'Vous avez du ravitaillement ?' WHERE `ID` = 41415 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Vous avez du ravitaillement ?', `FemaleText` = 'Vous avez du ravitaillement ?' WHERE `ID` = 45532 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je veux recommencer.', `FemaleText` = 'Je veux recommencer.' WHERE `ID` = 42004 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Echantillon d\'huile de cistude', `FemaleText` = 'Echantillon d\'huile de cistude' WHERE `ID` = 41998 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Oui, continuez s’il vous plaît.', `FemaleText` = 'Oui, continuez s’il vous plaît.' WHERE `ID` = 14507 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Apprenez-moi le dépeçage.', `FemaleText` = 'Apprenez-moi le dépeçage.' WHERE `ID` = 47117 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Archéologie', `FemaleText` = 'Archéologie' WHERE `ID` = 44649 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je vous transmets les salutations du roi Wrynn, $c. Vous trouverez derrière moi le tableau de l\'appel des héros, où sont affichées les proclamations du roi de Hurlevent pour guider les aventuriers là où leurs talents seront le plus utile pour l\'Alliance.' WHERE `ID` = 49765 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Druide', `FemaleText` = 'Druide' WHERE `ID` = 2914 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Druide', `FemaleText` = 'Druide' WHERE `ID` = 3446 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Druide', `FemaleText` = 'Druide' WHERE `ID` = 5342 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Druide', `FemaleText` = 'Druide' WHERE `ID` = 6701 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Druide', `FemaleText` = 'Druide' WHERE `ID` = 6922 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Druide', `FemaleText` = 'Druide' WHERE `ID` = 7080 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Druide', `FemaleText` = 'Druide' WHERE `ID` = 15236 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Druide', `FemaleText` = 'Druide' WHERE `ID` = 45409 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je cherche à progresser dans la voie du chasseur.', `FemaleText` = 'Je cherche à progresser dans la voie du chasseur.' WHERE `ID` = 7643 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Alchimie', `FemaleText` = 'Alchimie' WHERE `ID` = 7097 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Alchimie', `FemaleText` = 'Alchimie' WHERE `ID` = 15252 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Alchimie', `FemaleText` = 'Alchimie' WHERE `ID` = 19232 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Alchimie', `FemaleText` = 'Alchimie' WHERE `ID` = 45753 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Alchimie', `FemaleText` = 'Alchimie' WHERE `ID` = 52058 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Alchimie', `FemaleText` = 'Alchimie' WHERE `ID` = 2952 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Alchimie', `FemaleText` = 'Alchimie' WHERE `ID` = 3460 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Alchimie', `FemaleText` = 'Alchimie' WHERE `ID` = 4859 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Alchimie', `FemaleText` = 'Alchimie' WHERE `ID` = 5114 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Alchimie', `FemaleText` = 'Alchimie' WHERE `ID` = 5354 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Alchimie', `FemaleText` = 'Alchimie' WHERE `ID` = 5362 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Alchimie', `FemaleText` = 'Alchimie' WHERE `ID` = 5889 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Alchimie', `FemaleText` = 'Alchimie' WHERE `ID` = 6618 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Alchimie', `FemaleText` = 'Alchimie' WHERE `ID` = 6706 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Alchimie', `FemaleText` = 'Alchimie' WHERE `ID` = 6776 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Alchimie', `FemaleText` = 'Alchimie' WHERE `ID` = 6945 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Laboratoire d\'alchimie', `FemaleText` = 'Laboratoire d\'alchimie' WHERE `ID` = 20383 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Chasseur', `FemaleText` = 'Chasseur' WHERE `ID` = 45403 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Chasseur', `FemaleText` = 'Chasseur' WHERE `ID` = 50546 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Chasseur', `FemaleText` = 'Chasseur' WHERE `ID` = 2924 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Chasseur', `FemaleText` = 'Chasseur' WHERE `ID` = 3447 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Chasseur', `FemaleText` = 'Chasseur' WHERE `ID` = 4880 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Chasseur', `FemaleText` = 'Chasseur' WHERE `ID` = 5095 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Chasseur', `FemaleText` = 'Chasseur' WHERE `ID` = 5340 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Chasseur', `FemaleText` = 'Chasseur' WHERE `ID` = 6603 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Chasseur', `FemaleText` = 'Chasseur' WHERE `ID` = 6702 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Chasseur', `FemaleText` = 'Chasseur' WHERE `ID` = 6924 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Chasseur', `FemaleText` = 'Chasseur' WHERE `ID` = 7001 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Chasseur', `FemaleText` = 'Chasseur' WHERE `ID` = 7083 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Chasseur', `FemaleText` = 'Chasseur' WHERE `ID` = 15238 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'La banque', `FemaleText` = 'La banque' WHERE `ID` = 7066 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'La banque', `FemaleText` = 'La banque' WHERE `ID` = 4888 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'La banque', `FemaleText` = 'La banque' WHERE `ID` = 5326 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'La banque', `FemaleText` = 'La banque' WHERE `ID` = 6719 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'La banque', `FemaleText` = 'La banque' WHERE `ID` = 6789 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je veux qu\'on m\'enseigne la voie des prêtres.', `FemaleText` = 'Je veux qu\'on m\'enseigne la voie des prêtres.' WHERE `ID` = 7157 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je veux qu\'on m\'enseigne la voie des prêtres.', `FemaleText` = 'Je veux qu\'on m\'enseigne la voie des prêtres.' WHERE `ID` = 7160 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je veux qu\'on m\'enseigne la voie des prêtres.', `FemaleText` = 'Je veux qu\'on m\'enseigne la voie des prêtres.' WHERE `ID` = 7167 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Je veux qu\'on m\'enseigne la voie des prêtres.', `FemaleText` = 'Je veux qu\'on m\'enseigne la voie des prêtres.' WHERE `ID` = 7168 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je veux qu\'on m\'enseigne la voie des prêtres.', `FemaleText` = 'Je veux qu\'on m\'enseigne la voie des prêtres.' WHERE `ID` = 7169 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je voudrais en savoir plus sur les voies de la Lumière.', `FemaleText` = 'Je voudrais en savoir plus sur les voies de la Lumière.' WHERE `ID` = 5299 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'J\'ai une autre question.', `FemaleText` = 'J\'ai une autre question.' WHERE `ID` = 12241 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'J\'ai une autre question.', `FemaleText` = 'J\'ai une autre question.' WHERE `ID` = 12478 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'J\'ai une autre question.', `FemaleText` = 'J\'ai une autre question.' WHERE `ID` = 23442 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'J\'ai une autre question.', `FemaleText` = 'J\'ai une autre question.' WHERE `ID` = 59523 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'J\'ai une autre question.', `FemaleText` = 'J\'ai une autre question.' WHERE `ID` = 62310 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Nourriture et boissons', `FemaleText` = 'Nourriture et boissons' WHERE `ID` = 23962 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Nourriture et boissons', `FemaleText` = 'Nourriture et boissons' WHERE `ID` = 23755 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Nourriture et boissons', `FemaleText` = 'Nourriture et boissons' WHERE `ID` = 66664 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Jetons & souvenirs', `FemaleText` = 'Jetons & souvenirs' WHERE `ID` = 23756 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'La mise en perce', `FemaleText` = 'La mise en perce' WHERE `ID` = 23877 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Pêche', `FemaleText` = 'Pêche' WHERE `ID` = 32144 AND `Language` = ;
UPDATE `broadcast_text` SET `MaleText` = 'Pêche', `FemaleText` = 'Pêche' WHERE `ID` = 45436 AND `Language` = ;
UPDATE `broadcast_text` SET `MaleText` = 'Pêche', `FemaleText` = 'Pêche' WHERE `ID` = 45767 AND `Language` = ;
UPDATE `broadcast_text` SET `MaleText` = 'Pêche', `FemaleText` = 'Pêche' WHERE `ID` = 3005 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Pêche', `FemaleText` = 'Pêche' WHERE `ID` = 3465 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Pêche', `FemaleText` = 'Pêche' WHERE `ID` = 4864 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Pêche', `FemaleText` = 'Pêche' WHERE `ID` = 5127 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Pêche', `FemaleText` = 'Pêche' WHERE `ID` = 5368 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Pêche', `FemaleText` = 'Pêche' WHERE `ID` = 5895 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Pêche', `FemaleText` = 'Pêche' WHERE `ID` = 6624 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Pêche', `FemaleText` = 'Pêche' WHERE `ID` = 6711 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Pêche', `FemaleText` = 'Pêche' WHERE `ID` = 6782 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Pêche', `FemaleText` = 'Pêche' WHERE `ID` = 6951 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Pêche', `FemaleText` = 'Pêche' WHERE `ID` = 7030 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Pêche', `FemaleText` = 'Pêche' WHERE `ID` = 7109 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Pêche', `FemaleText` = 'Pêche' WHERE `ID` = 15263 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Forge', `FemaleText` = 'Forge' WHERE `ID` = 19249 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Forge', `FemaleText` = 'Forge' WHERE `ID` = 45754 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Forge', `FemaleText` = 'Forge' WHERE `ID` = 51346 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Forge', `FemaleText` = 'Forge' WHERE `ID` = 2942 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Forge', `FemaleText` = 'Forge' WHERE `ID` = 3461 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Forge', `FemaleText` = 'Forge' WHERE `ID` = 4860 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Forge', `FemaleText` = 'Forge' WHERE `ID` = 5117 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Forge', `FemaleText` = 'Forge' WHERE `ID` = 5890 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Forge', `FemaleText` = 'Forge' WHERE `ID` = 6619 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Forge', `FemaleText` = 'Forge' WHERE `ID` = 6707 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Forge', `FemaleText` = 'Forge' WHERE `ID` = 6777 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Forge', `FemaleText` = 'Forge' WHERE `ID` = 6946 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Forge', `FemaleText` = 'Forge' WHERE `ID` = 7025 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Forge', `FemaleText` = 'Forge' WHERE `ID` = 15255 AND `Language` = 0;

UPDATE `broadcast_text` SET `MaleText` = 'Cuisine', `FemaleText` = 'Cuisine' WHERE `ID` = 16029 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Cuisine', `FemaleText` = 'Cuisine' WHERE `ID` = 19233 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Cuisine', `FemaleText` = 'Cuisine' WHERE `ID` = 45432 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Cuisine', `FemaleText` = 'Cuisine' WHERE `ID` = 45763 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Cuisine', `FemaleText` = 'Cuisine' WHERE `ID` = 2945 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Cuisine', `FemaleText` = 'Cuisine' WHERE `ID` = 3462 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Cuisine', `FemaleText` = 'Cuisine' WHERE `ID` = 4861 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Cuisine', `FemaleText` = 'Cuisine' WHERE `ID` = 5119 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Cuisine', `FemaleText` = 'Cuisine' WHERE `ID` = 5356 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Cuisine', `FemaleText` = 'Cuisine' WHERE `ID` = 5891 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Cuisine', `FemaleText` = 'Cuisine' WHERE `ID` = 6620 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Cuisine', `FemaleText` = 'Cuisine' WHERE `ID` = 6708 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Cuisine', `FemaleText` = 'Cuisine' WHERE `ID` = 6778 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Cuisine', `FemaleText` = 'Cuisine' WHERE `ID` = 6947 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Cuisine', `FemaleText` = 'Cuisine' WHERE `ID` = 7026 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Cuisine', `FemaleText` = 'Cuisine' WHERE `ID` = 7100 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Mage', `FemaleText` = 'Mage' WHERE `ID` = 15240 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Mage', `FemaleText` = 'Mage' WHERE `ID` = 45404 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Mage', `FemaleText` = 'Mage' WHERE `ID` = 2902 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Mage', `FemaleText` = 'Mage' WHERE `ID` = 3448 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Mage', `FemaleText` = 'Mage' WHERE `ID` = 4882 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Mage', `FemaleText` = 'Mage' WHERE `ID` = 5097 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Mage', `FemaleText` = 'Mage' WHERE `ID` = 5902 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Mage', `FemaleText` = 'Mage' WHERE `ID` = 6604 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Mage', `FemaleText` = 'Mage' WHERE `ID` = 6770 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Mage', `FemaleText` = 'Mage' WHERE `ID` = 6929 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Mage', `FemaleText` = 'Mage' WHERE `ID` = 7004 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'L\'éleveur de chauve-souris', `FemaleText` = 'L\'éleveur de chauve-souris' WHERE `ID` = 6790 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Paladin', `FemaleText` = 'Paladin' WHERE `ID` = 6932 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Paladin', `FemaleText` = 'Paladin' WHERE `ID` = 7007 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Paladin', `FemaleText` = 'Paladin' WHERE `ID` = 15242 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Paladin', `FemaleText` = 'Paladin' WHERE `ID` = 18362 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Paladin', `FemaleText` = 'Paladin' WHERE `ID` = 20974 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Paladin', `FemaleText` = 'Paladin' WHERE `ID` = 48028 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Paladin', `FemaleText` = 'Paladin' WHERE `ID` = 2922 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Paladin', `FemaleText` = 'Paladin' WHERE `ID` = 5102 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Le maître des coursiers du vent', `FemaleText` = 'Le maître des coursiers du vent' WHERE `ID` = 6720 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Chaman', `FemaleText` = 'Chaman' WHERE `ID` = 18321 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Chaman', `FemaleText` = 'Chaman' WHERE `ID` = 20973 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Chaman', `FemaleText` = 'Chaman' WHERE `ID` = 45410 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Chaman', `FemaleText` = 'Chaman' WHERE `ID` = 3450 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Chaman', `FemaleText` = 'Chaman' WHERE `ID` = 4884 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Chaman', `FemaleText` = 'Chaman' WHERE `ID` = 6606 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Chaman', `FemaleText` = 'Chaman' WHERE `ID` = 6703 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Prêtre', `FemaleText` = 'Prêtre' WHERE `ID` = 6771 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Prêtre', `FemaleText` = 'Prêtre' WHERE `ID` = 6926 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Prêtre', `FemaleText` = 'Prêtre' WHERE `ID` = 7010 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Prêtre', `FemaleText` = 'Prêtre' WHERE `ID` = 7086 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Prêtre', `FemaleText` = 'Prêtre' WHERE `ID` = 15241 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Prêtre', `FemaleText` = 'Prêtre' WHERE `ID` = 45405 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Prêtre', `FemaleText` = 'Prêtre' WHERE `ID` = 2918 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Prêtre', `FemaleText` = 'Prêtre' WHERE `ID` = 3449 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Prêtre', `FemaleText` = 'Prêtre' WHERE `ID` = 4883 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Prêtre', `FemaleText` = 'Prêtre' WHERE `ID` = 5100 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Prêtre', `FemaleText` = 'Prêtre' WHERE `ID` = 5344 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Prêtre', `FemaleText` = 'Prêtre' WHERE `ID` = 5903 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Prêtre', `FemaleText` = 'Prêtre' WHERE `ID` = 6605 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des hippogriffes', `FemaleText` = 'Maître des hippogriffes' WHERE `ID` = 17019 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des hippogriffes', `FemaleText` = 'Maître des hippogriffes' WHERE `ID` = 18292 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître des hippogriffes', `FemaleText` = 'Maître des hippogriffes' WHERE `ID` = 5330 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Je cherche un compagnon perdu.', `FemaleText` = 'Je cherche un compagnon perdu.' WHERE `ID` = 56613 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'J\'ai besoin d\'une formation, Zamja.', `FemaleText` = 'J\'ai besoin d\'une formation, Zamja.' WHERE `ID` = 8347 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Fournitures d\'artisanat', `FemaleText` = 'Fournitures d\'artisanat' WHERE `ID` = 32719 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Fournitures d\'artisanat', `FemaleText` = 'Fournitures d\'artisanat' WHERE `ID` = 45445 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Le maître de vol', `FemaleText` = 'Le maître de vol' WHERE `ID` = 4889 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Le maître de vol', `FemaleText` = 'Le maître de vol' WHERE `ID` = 6632 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Le maître de vol', `FemaleText` = 'Le maître de vol' WHERE `ID` = 19203 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Le maître de vol', `FemaleText` = 'Le maître de vol' WHERE `ID` = 45379 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Le maître de vol', `FemaleText` = 'Le maître de vol' WHERE `ID` = 2863 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Maîtres de guerre de l\'Alliance', `FemaleText` = 'Maîtres de guerre de l\'Alliance' WHERE `ID` = 19227 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maîtres de guerre de la Horde', `FemaleText` = 'Maîtres de guerre de la Horde' WHERE `ID` = 19228 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maîtres de guerre des arènes', `FemaleText` = 'Maîtres de guerre des arènes' WHERE `ID` = 25121 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Faites-vous des réparations ?', `FemaleText` = 'Faites-vous des réparations ?' WHERE `ID` = 45533 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Retouche', `FemaleText` = 'Retouche' WHERE `ID` = 50622 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Maître de guerre de l\'arène', `FemaleText` = 'Maître de guerre de l\'arène' WHERE `ID` = 18610 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Travail du cuir', `FemaleText` = 'Travail du cuir' WHERE `ID` = 19236 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Travail du cuir', `FemaleText` = 'Travail du cuir' WHERE `ID` = 45759 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Travail du cuir', `FemaleText` = 'Travail du cuir' WHERE `ID` = 52071 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Travail du cuir', `FemaleText` = 'Travail du cuir' WHERE `ID` = 2947 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Travail du cuir', `FemaleText` = 'Travail du cuir' WHERE `ID` = 3467 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Travail du cuir', `FemaleText` = 'Travail du cuir' WHERE `ID` = 15269 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Travail du cuir', `FemaleText` = 'Travail du cuir' WHERE `ID` = 7115 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Travail du cuir', `FemaleText` = 'Travail du cuir' WHERE `ID` = 7032 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Travail du cuir', `FemaleText` = 'Travail du cuir' WHERE `ID` = 6953 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Travail du cuir', `FemaleText` = 'Travail du cuir' WHERE `ID` = 6784 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Travail du cuir', `FemaleText` = 'Travail du cuir' WHERE `ID` = 6713 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Travail du cuir', `FemaleText` = 'Travail du cuir' WHERE `ID` = 6626 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Travail du cuir', `FemaleText` = 'Travail du cuir' WHERE `ID` = 5897 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Travail du cuir', `FemaleText` = 'Travail du cuir' WHERE `ID` = 5133 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Travail du cuir', `FemaleText` = 'Travail du cuir' WHERE `ID` = 5371 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Travail du cuir', `FemaleText` = 'Travail du cuir' WHERE `ID` = 4866 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Démoniste', `FemaleText` = 'Démoniste' WHERE `ID` = 45407 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Démoniste', `FemaleText` = 'Démoniste' WHERE `ID` = 2926 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Démoniste', `FemaleText` = 'Démoniste' WHERE `ID` = 4886 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Démoniste', `FemaleText` = 'Démoniste' WHERE `ID` = 5108 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Démoniste', `FemaleText` = 'Démoniste' WHERE `ID` = 5905 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Démoniste', `FemaleText` = 'Démoniste' WHERE `ID` = 6615 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Démoniste', `FemaleText` = 'Démoniste' WHERE `ID` = 6773 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Démoniste', `FemaleText` = 'Démoniste' WHERE `ID` = 6941 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Démoniste', `FemaleText` = 'Démoniste' WHERE `ID` = 7016 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Démoniste', `FemaleText` = 'Démoniste' WHERE `ID` = 15244 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Voleur', `FemaleText` = 'Voleur' WHERE `ID` = 45406 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Voleur', `FemaleText` = 'Voleur' WHERE `ID` = 2906 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Voleur', `FemaleText` = 'Voleur' WHERE `ID` = 4885 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Voleur', `FemaleText` = 'Voleur' WHERE `ID` = 5105 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Voleur', `FemaleText` = 'Voleur' WHERE `ID` = 5347 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Voleur', `FemaleText` = 'Voleur' WHERE `ID` = 5904 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Voleur', `FemaleText` = 'Voleur' WHERE `ID` = 6608 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Voleur', `FemaleText` = 'Voleur' WHERE `ID` = 6772 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Voleur', `FemaleText` = 'Voleur' WHERE `ID` = 6935 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Voleur', `FemaleText` = 'Voleur' WHERE `ID` = 7013 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Voleur', `FemaleText` = 'Voleur' WHERE `ID` = 7089 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Voleur', `FemaleText` = 'Voleur' WHERE `ID` = 15243 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Mage & Portail', `FemaleText` = 'Mage & Portail' WHERE `ID` = 45411 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Gymer, qu\'y a-t-il à savoir ? Je n\'ai jamais chevauché un géant.', `FemaleText` = 'Gymer, qu\'y a-t-il à savoir ? Je n\'ai jamais chevauché un géant.' WHERE `ID` = 30616 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Marchand', `FemaleText` = 'Marchand' WHERE `ID` = 44612 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Endroits intéressants', `FemaleText` = 'Endroits intéressants' WHERE `ID` = 32180 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Joaillerie', `FemaleText` = 'Joaillerie' WHERE `ID` = 44647 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Joaillerie', `FemaleText` = 'Joaillerie' WHERE `ID` = 45758 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Joaillerie', `FemaleText` = 'Joaillerie' WHERE `ID` = 15267 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Joaillerie', `FemaleText` = 'Joaillerie' WHERE `ID` = 18338 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Joaillerie', `FemaleText` = 'Joaillerie' WHERE `ID` = 19235 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Dépeçage', `FemaleText` = 'Dépeçage' WHERE `ID` = 19237 AND `Language` = ;
UPDATE `broadcast_text` SET `MaleText` = 'Dépeçage', `FemaleText` = 'Dépeçage' WHERE `ID` = 45770 AND `Language` = ;
UPDATE `broadcast_text` SET `MaleText` = 'Dépeçage', `FemaleText` = 'Dépeçage' WHERE `ID` = 52076 AND `Language` = ;
UPDATE `broadcast_text` SET `MaleText` = 'Dépeçage', `FemaleText` = 'Dépeçage' WHERE `ID` = 2948 AND `Language` = 7;
UPDATE `broadcast_text` SET `MaleText` = 'Dépeçage', `FemaleText` = 'Dépeçage' WHERE `ID` = 4869 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Dépeçage', `FemaleText` = 'Dépeçage' WHERE `ID` = 5140 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Dépeçage', `FemaleText` = 'Dépeçage' WHERE `ID` = 5376 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Dépeçage', `FemaleText` = 'Dépeçage' WHERE `ID` = 5899 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Dépeçage', `FemaleText` = 'Dépeçage' WHERE `ID` = 3471 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Dépeçage', `FemaleText` = 'Dépeçage' WHERE `ID` = 6628 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Dépeçage', `FemaleText` = 'Dépeçage' WHERE `ID` = 6716 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Dépeçage', `FemaleText` = 'Dépeçage' WHERE `ID` = 6786 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Dépeçage', `FemaleText` = 'Dépeçage' WHERE `ID` = 6955 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Dépeçage', `FemaleText` = 'Dépeçage' WHERE `ID` = 7034 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Dépeçage', `FemaleText` = 'Dépeçage' WHERE `ID` = 7118 AND `Language` = 0;
UPDATE `broadcast_text` SET `MaleText` = 'Dépeçage', `FemaleText` = 'Dépeçage' WHERE `ID` = 15273 AND `Language` = 0;